/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicV1HoldingsRouteImport } from './routes/api/public/v1/holdings'
import { Route as ApiPublicV1HoldingsSymbolRouteImport } from './routes/api/public/v1/holdings.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1HoldingsRoute = ApiPublicV1HoldingsRouteImport.update({
  id: '/api/public/v1/holdings',
  path: '/api/public/v1/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1HoldingsSymbolRoute =
  ApiPublicV1HoldingsSymbolRouteImport.update({
    id: '/$symbol',
    path: '/$symbol',
    getParentRoute: () => ApiPublicV1HoldingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/v1/holdings': typeof ApiPublicV1HoldingsRouteWithChildren
  '/api/public/v1/holdings/$symbol': typeof ApiPublicV1HoldingsSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/v1/holdings': typeof ApiPublicV1HoldingsRouteWithChildren
  '/api/public/v1/holdings/$symbol': typeof ApiPublicV1HoldingsSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/v1/holdings': typeof ApiPublicV1HoldingsRouteWithChildren
  '/api/public/v1/holdings/$symbol': typeof ApiPublicV1HoldingsSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/v1/holdings' | '/api/public/v1/holdings/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/v1/holdings' | '/api/public/v1/holdings/$symbol'
  id:
    | '__root__'
    | '/'
    | '/api/public/v1/holdings'
    | '/api/public/v1/holdings/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicV1HoldingsRoute: typeof ApiPublicV1HoldingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/holdings': {
      id: '/api/public/v1/holdings'
      path: '/api/public/v1/holdings'
      fullPath: '/api/public/v1/holdings'
      preLoaderRoute: typeof ApiPublicV1HoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/holdings/$symbol': {
      id: '/api/public/v1/holdings/$symbol'
      path: '/$symbol'
      fullPath: '/api/public/v1/holdings/$symbol'
      preLoaderRoute: typeof ApiPublicV1HoldingsSymbolRouteImport
      parentRoute: typeof ApiPublicV1HoldingsRoute
    }
  }
}

interface ApiPublicV1HoldingsRouteChildren {
  ApiPublicV1HoldingsSymbolRoute: typeof ApiPublicV1HoldingsSymbolRoute
}

const ApiPublicV1HoldingsRouteChildren: ApiPublicV1HoldingsRouteChildren = {
  ApiPublicV1HoldingsSymbolRoute: ApiPublicV1HoldingsSymbolRoute,
}

const ApiPublicV1HoldingsRouteWithChildren =
  ApiPublicV1HoldingsRoute._addFileChildren(ApiPublicV1HoldingsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicV1HoldingsRoute: ApiPublicV1HoldingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
